### ISSUE TITLE
HP Bar Glitch

### ISSUE THREAD

**Issue by Mooncat25** [NiftyManiac/factorio-stickynotes#14]
This happens occasionally, after the sticky note is mined. I doubt it is because its max health is 0.

![20170217013445_1](https://cloud.githubusercontent.com/assets/7956390/23036435/c9be0b86-f4bd-11e6-8cb6-d1c95a52f9c0.jpg)

**Comment by NiftyManiac** [comment]
Fixed in https://github.com/NiftyManiac/factorio-stickynotes/commit/e456dbbe379b37a401c3428eec8bca7910980e33 by making the health not 0 :). @Nexela made it 0 for some reason, no idea why. They should be destructible like anything else.

**Comment by NiftyManiac** [comment]
Huh actually they were always indestructible. Oh well, guess I'll leave it for now. They'll be indestructible with 50 health.

**Comment by Nexela** [comment]
I made them 0 because typically they are indestructible. I think the health bars are a Factorio bug on old entities (entities placed before max health change).  I can't remember but I think this has been reported and fixed for .15.  I had the same issue when lowering the ammo count on nanobots, All older ammos had a long bar.

**Comment by Nexela** [comment]
I did a quick google search and couldn't find the bug report so I will make one later tonight unless you beat me too it :)

Also if you put Closes #issuenumber or Fixes #issuenumber in your commit then when merged into master it will auto close the issue with a link to the commit

**Comment by NiftyManiac** [comment]
Good to know!
